from math import pi

# CAR CONSTANTS

DIVIDER_SPEED = 0.02
DIVIDER_BREAK = 0.01
DIVIDER_ANGLE_INPUT = 1.2
DIVIDER_ANGLE = 0.1
CAR_SPEED = 3.6
DISTANCE_TO_TRIGGER_CHECKS = 3.1

# MATH CCONSTANTS

MAX_RADIANS = 2 * pi

# SCREEN CONSTANTS

SCREEN_WIDTH = 1200
SCREEN_HEIGHT = 600
FPS = 50

# TRACK CONSTANTS

X_SECTOR_NO = 100
Y_SECTOR_NO = 60
X_SECTOR_SIZE = SCREEN_WIDTH // X_SECTOR_NO
Y_SECTOR_SIZE = SCREEN_HEIGHT // Y_SECTOR_NO

# OTHER

CARS_NO = 30
# CARS_NO = 1
